expenses = [
    {"data": "12/05", "cidade": "Pequim", "descricao": "Didi pro templo do céu (tava fechado)", "valor": 38.42, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Didi pro shopping das Pérolas (Hungqiao Market)", "valor": 13.30, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Colar e brincos Carol + brinco presente da Lara", "valor": 170.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Didi pra Qianmen", "valor": 14.80, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Almoço Qianmen", "valor": 64.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Sorvete de amendoim", "valor": 9.90, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Metrô", "valor": 6.00, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Mountain Coffee", "valor": 25.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "3 Baralhos", "valor": 90.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Didi pra casa", "valor": 45.00, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "12/05", "cidade": "Pequim", "descricao": "Didi pro restaurante de dumpling fritos", "valor": 49.93, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Didi pro Templo do Céu", "valor": 45.00, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Ingresso Templo do Céu", "valor": 34.00, "quem_pagou": "Carol", "categoria": "Ingressos"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Icetea de limão", "valor": 8.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Bolsa e marcador de página", "valor": 78.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Metrô", "valor": 10.00, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Pequim", "descricao": "Didi pra Beijingbei", "valor": 53.73, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Didi pro Hotel Weidu em Datong", "valor": 18.20, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Dois cafés da manhã do hotel", "valor": 116.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Didi pro restaurante Zini 369", "valor": 7.30, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Jantar Zini 369", "valor": 66.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Suco de maçã", "valor": 7.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "13/05", "cidade": "Datong", "descricao": "Didi pro hotel", "valor": 7.50, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Entrada Hanging Temple", "valor": 115.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Ônibus Hanging Temple", "valor": 40.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Café KFC", "valor": 20.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Comprinhas souvenirs Hanging Temple", "valor": 97.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Almoço Yunjinhui", "valor": 232.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Sinos de souvenir", "valor": 40.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Cadernos Datong", "valor": 75.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "14/05", "cidade": "Datong", "descricao": "Lencinhos", "valor": 5.40, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "15/05", "cidade": "Datong", "descricao": "Ônibus Yungang Grottoes", "valor": 30.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "15/05", "cidade": "Datong", "descricao": "Comprinhas souvenir", "valor": 87.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "15/05", "cidade": "Datong", "descricao": "Sucos", "valor": 30.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "15/05", "cidade": "Datong", "descricao": "Táxi pra estação", "valor": 19.80, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "15/05", "cidade": "Pequim", "descricao": "Metrô pra casa", "valor": 10.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Águas", "valor": 8.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Almoço", "valor": 115.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Táxi Summer Palace", "valor": 54.50, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Entrada Summer Palace", "valor": 60.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Audioguia Summer Palace", "valor": 40.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Água saborizada Summer Palace", "valor": 8.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Bolachas de amêndoa", "valor": 25.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Metrô para o Migas", "valor": 10.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "16/05", "cidade": "Pequim", "descricao": "Jantar no Migas (espanhol)", "valor": 645.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Didi pra estação Beijingnan", "valor": 47.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Wrap de frango", "valor": 39.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Café de balde", "valor": 44.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Frutinhas", "valor": 17.90, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Metrô", "valor": 10.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Balde de frango", "valor": 20.98, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Metrô", "valor": None, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Leques", "valor": 20.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Prendedor de cabelo", "valor": 20.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "17/05", "cidade": "Pequim", "descricao": "Jantar", "valor": 303.00, "quem_pagou": "Tica", "categoria": "Alimentação"},
    {"data": "18/05", "cidade": "Suzhou", "descricao": "Metro", "valor": 4.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "18/05", "cidade": "Suzhou", "descricao": "Entrada Jardim do Administrador Humilde", "valor": 80.00, "quem_pagou": "Carol", "categoria": "Ingressos"},
    {"data": "18/05", "cidade": "Suzhou", "descricao": "Entrada Jardim do Administrador Humilde", "valor": 40.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "18/05", "cidade": "Suzhou", "descricao": "Cartão-postal", "valor": 10.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "18/05", "cidade": "Suzhou", "descricao": "Café espresso + leite", "valor": 20.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "18/05", "cidade": "Xangai", "descricao": "Passagem avião Xangai-Pequim", "valor": 1460.00, "quem_pagou": "Tica", "categoria": "Transporte"},
    {"data": "18/05", "cidade": "Xangai", "descricao": "Táxi pro hotel", "valor": 27.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "18/05", "cidade": "Xangai", "descricao": "Jantar", "valor": 99.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Café da manhã do hotel", "valor": 76.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Didi pro barco", "valor": 14.50, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Barco", "valor": 4.00, "quem_pagou": "Cada uma", "categoria": "Transporte"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Didi pro museu", "valor": 14.50, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "MAP Museum of Art of Pudong", "valor": 180.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Alguma coisa de 2 yuan", "valor": 2.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Comprinhas museu Pudong", "valor": 18.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Almoço Starbucks, wrap de frango e frutas", "valor": 57.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Coquinha", "valor": 6.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Ingresso torre Pérola Oriental", "valor": 256.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Comprinhas na torre", "valor": 83.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Comprinhas na torre", "valor": 66.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Uniqlo haul", "valor": 1162.00, "quem_pagou": "Paula", "categoria": "Compras/Presentes"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Didi pro The Captain", "valor": 39.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Jantar 2 no espetinho", "valor": 112.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "19/05", "cidade": "Xangai", "descricao": "Lenços no mercadinho ao lado do hotel", "valor": 11.80, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Café da manhã do hotel", "valor": 76.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Didi pro Yuyuan", "valor": 18.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Comprinhas", "valor": 120.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Ingresso Yuyuan", "valor": 60.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Guarda-chuva + água", "valor": 44.40, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Miniso meia e fone", "valor": 44.90, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Chocolates e carrinho Inácio", "valor": 128.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Almoço dumplings", "valor": 32.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Metrô", "valor": 6.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Sorvete de casquinha", "valor": 42.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "20/05", "cidade": "Xangai", "descricao": "Metrô aeroporto", "valor": 8.00, "quem_pagou": "Cada uma", "categoria": "Transporte"},
    {"data": "20/05", "cidade": "Pequim", "descricao": "Jantar Carol", "valor": 26.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "20/05", "cidade": "Pequim", "descricao": "Didi pra casa", "valor": 77.88, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "21/05", "cidade": "Pequim", "descricao": "Didi na ida", "valor": 187.27, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "21/05", "cidade": "Pequim", "descricao": "Ingressos parque + shuttle + bondinho", "valor": 400.00, "quem_pagou": "Paula", "categoria": "Ingressos"},
    {"data": "21/05", "cidade": "Pequim", "descricao": "Chapéu", "valor": 40.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "21/05", "cidade": "Pequim", "descricao": "Almoço Saigon Baimen", "valor": 108.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "21/05", "cidade": "Pequim", "descricao": "Didi na volta", "valor": 204.20, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "22/05", "cidade": "Pequim", "descricao": "Didi para Tiannanmen", "valor": None, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "22/05", "cidade": "Pequim", "descricao": "Almoço no museu", "valor": None, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "22/05", "cidade": "Pequim", "descricao": "Comprinhas museu", "valor": None, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "22/05", "cidade": "Pequim", "descricao": "Volta de metrô", "valor": 8.00, "quem_pagou": "Cada uma", "categoria": "Transporte"},
    {"data": "23/05", "cidade": "Pequim", "descricao": "Metrô pra Cidade Proibida", "valor": 9.00, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "23/05", "cidade": "Pequim", "descricao": "Entrada Cidade Proibida", "valor": 60.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "24/05", "cidade": "Lhasa", "descricao": "Didi pro aeroporto", "valor": None, "quem_pagou": "Carol", "categoria": "Transporte"},
    {"data": "24/05", "cidade": "Lhasa", "descricao": "Almoço hot pot surpresa", "valor": 438.00, "quem_pagou": "Tica", "categoria": "Alimentação"},
    {"data": "24/05", "cidade": "Lhasa", "descricao": "Show Princesa Wejcheng", "valor": 840.00, "quem_pagou": "Tica", "categoria": "Ingressos"},
    {"data": "24/05", "cidade": "Lhasa", "descricao": "Comidas", "valor": 30.00, "quem_pagou": "Carol/Renata", "categoria": "Alimentação"},
    {"data": "25/05", "cidade": "Lhasa", "descricao": "Proteção (Jokar Temple)", "valor": 50.00, "quem_pagou": "Renata", "categoria": "Compras/Presentes"},
    {"data": "25/05", "cidade": "Lhasa", "descricao": "Porta-incenso e ímã", "valor": 76.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "25/05", "cidade": "Lhasa", "descricao": "Bolsas", "valor": 120.00, "quem_pagou": "Tica", "categoria": "Compras/Presentes"},
    {"data": "26/05", "cidade": "Lhasa", "descricao": "Comprinhas mirante", "valor": 150.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "27/05", "cidade": "Shigatse", "descricao": "Gorjeta Samsara e Kunga", "valor": 100.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "27/05", "cidade": "Shigatse", "descricao": "Jantar", "valor": None, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Chapéu", "valor": 35.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Copinhos", "valor": 50.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Comprinhas no Old Market", "valor": 125.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Almoço", "valor": 45.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Gorjeta Lhakdon", "valor": 30.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Água e cerveja", "valor": 13.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Comprinhas", "valor": 50.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Jantar Pizza Hut", "valor": 57.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "28/05", "cidade": "Shigatse", "descricao": "Suco", "valor": 12.00, "quem_pagou": "Carol", "categoria": "Alimentação"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Didi para Norbulingka", "valor": 15.00, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Entrada Norbulingka", "valor": 120.00, "quem_pagou": "Diva", "categoria": "Ingressos"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Compras Norbulingka", "valor": 308.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Didi para Bokar", "valor": None, "quem_pagou": "Diva", "categoria": "Transporte"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Almoço", "valor": 33.00, "quem_pagou": "Diva", "categoria": "Alimentação"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Compras Bokar Supermarket", "valor": 105.00, "quem_pagou": "Carol", "categoria": "Compras/Presentes"},
    {"data": "29/05", "cidade": "Lhasa", "descricao": "Massagem no aeroporto", "valor": 30.00, "quem_pagou": "Diva", "categoria": "Compras/Presentes"},
    {"data": "29/05", "cidade": "Pequim", "descricao": "Taxi do aeroporto", "valor": 102.00, "quem_pagou": "Paula", "categoria": "Transporte"}
]